name: Small infrastructure
network:
  name: Small network
  segments:
    -
      name: Segment 1
      innerBandwith: [100, 100]
      outerBandwith: [50, 50]
      nodes:
        -
          name: Node A
          agents:
            -
              name: Dummy 1.1
              type: dummy
    -
      name: Segment 2
      innerBandwith: [100, 100]
      outerBandwith: [50, 50]
      nodes:
        -
          name: Node B
          agents:
            -
              name: Dummy 2.1
              type: dummy
        -
          name: Node C
          agents:
            -
              name: Dummy 2.2
              type: dummy
